backend:
  name: github
  repo: broadinstitute/gnomad-blog
  branch: main
  base_url: https://gnomad.broadinstitute.org
  auth_endpoint: /blog/auth/
  preview_context: actions/deploy

site_url: https://gnomad.broadinstitute.org/blog/

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: "{{slug}}/"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Relative order"
        hint: "Relative order for multiple posts published on the same date."
        name: "order"
        widget: "number"
        value_type: "int"
        default: 1
        min: 1
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
      - label: "Authors"
        name: "authors"
        widget: "list"
      - label: "Body"
        name: "body"
        widget: "markdown"
