name: Delete preview
on:
  pull_request:
    types:
      - closed
jobs:
  delete-preview:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCS_SA_EMAIL }}
          service_account_key: ${{ secrets.GCS_SA_KEY }}

      - name: Delete preview
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gsutil -mq rm -r "gs://gnomad-blog/pulls/${pr_number}"
